### ISSUE TITLE
openBabelPlot adds Hydrogens to Cl-

### ISSUE THREAD

**Issue by StLeonidas** [girke-lab/ChemmineR#7]
Function openBabelPlot adds hydrogen to Cl- ion and N+ counterion though it doesn't do such a thing with I- ion.
Tested with C[N+]1=CC=C(C=C1)C.[Cl-] and C[N+]1=CC=C(C=C1)C.[I-] correspondingly.

**Comment by khoran** [comment]
I think that is an issue with OpenBabel. Do you get different results if you use obabel command line directly? 
The openBabelPlot function essentially just sets the "-d" option if `noHbonds=TRUE`, and leaves the option off otherwise. You can set your own options by calling the `convertToImage` function in the ChemmineOB package.

**Comment by StLeonidas** [comment]
Yes, same results with obabal command line.
Appreciate your support!
